#
#
#



#
#
#

all: ExampleScalaGet PhaseTwo

ExampleScalaGet: ExampleScalaGet.class

ExampleScalaGet.class: ExampleScalaGet.scala
	scalac $<

PhaseTwo: PhaseTwo.class

PhaseTwo.class: phase2.scala
	scalac $<

